# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1157-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/sources_1/imports/AWGN/LZD_2bit.v}
  {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/sources_1/imports/AWGN/LZD_16bit.v}
  {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/sources_1/imports/AWGN/barrel_shifter_48.v}
  {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/sources_1/imports/AWGN/LZD_32bit.v}
  {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/sources_1/imports/AWGN/barrel_shifter_48_right.v}
  {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/sources_1/imports/AWGN/cosine_module.v}
  {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/sources_1/imports/AWGN/log_module.v}
  {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/sources_1/imports/AWGN/sqrt_module.v}
  {C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/sources_1/imports/AWGN/AWGN.v}
}
read_xdc {{C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/constrs_1/imports/AWGN_IP/AWGN.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Santosh/Desktop/Xilinx Vivado Projects/AWGN/AWGN.srcs/constrs_1/imports/AWGN_IP/AWGN.xdc}}]

synth_design -top AWGN -part xc7vx690tffg1157-3
write_checkpoint -noxdef AWGN.dcp
catch { report_utilization -file AWGN_utilization_synth.rpt -pb AWGN_utilization_synth.pb }
